### ISSUE TITLE
Why the form for user is created in javascript?

### ISSUE THREAD

**Issue by KrzysztofMadejski** [the-engine-room/replication-sprint-02#1]
It feels counterintuitive for me for the form to be created in javascript views instead of html views.

If there is no strong argument for that I'd vote for rewriting this part if there is time.

**Comment by georgeslabreche** [comment]
@KrzysztofMadejski what do you mean by "javascript views"? Can you please include a reference to the block of code in question?

A bit of a background, in case it sheds light on things: Crowdata is meant to dynamically build forms based on admin tools. Maybe this is why there is what you call "javascript views"? Anyhow, implementation of Quien Compro ended up making the dynamic form building logic useless because at the end of the day we had a specific layout that was designed which was not possible to render dynamically.

**Comment by KrzysztofMadejski** [comment]
Forget "javascript views", maybe I've meant computing reports html code: https://github.com/the-engine-room/replication-sprint-02/blob/master/crowdataapp/templates/document_set_index.html#L30-L60

**Comment by KrzysztofMadejski** [comment]
Ok, by "javascript views" I've meant all the form generated by javascript in https://github.com/the-engine-room/replication-sprint-02/blob/master/templates/forms/includes/built_form.html#L86-L89 by `qs.js` instead of using auto-generated forms at https://github.com/the-engine-room/replication-sprint-02/blob/master/templates/forms/includes/built_form.html#L66-L77. 

Also custom multiline items code in https://github.com/the-engine-room/replication-sprint-02/blob/master/templates/forms/includes/built_form.html#L70t

Why have you taken such approach? To deliver working solution I guess?

**Comment by georgeslabreche** [comment]
The dynamic form builder just generated a label/field per line whereas the requirements for the form layout in QuienCompro were much more elaborate.

**Comment by KrzysztofMadejski** [comment]
Hm, now I see that. Some helpers, grouping fields, etc.

**Comment by KrzysztofMadejski** [comment]
So actually is there a need to define document set fields? Cause I don't see description and precio defined in Quien Compro for example./ Do document set fields play any role in verification? @partini ?

**Comment by partini** [comment]
@KrzysztofMadejski the precio, description field are added dynamically to ReceiptItem field, if you go to Admin/Document set, and scroll to the bottom of the page you will see the form fields. If that's what you are referring with document set fields than yes, they play a role in verification, you have a verify column(checkboxes) which is taken into account to consider a document as verified.
Did I answer your question?
<img width="1323" alt="screen shot 2017-01-25 at 11 40 42 am" src="https://cloud.githubusercontent.com/assets/7932995/22287423/2bd0d52e-e2f3-11e6-8c2d-59008a4b463d.png">

**Comment by KrzysztofMadejski** [comment]
Yes, thank you! And the multivalues fields are joined together while sending the form I see.
```
POSTed to http://entretodos.theengineroom.org/cd/crowdata/form/quien-compro
receiptitem-29
fecha_de_facturacion
fecha_de_facturaciono
domicilio_fisico_del_emisor_physical_address
razon_social_del_emisor
nombre_comerical_de_emisor
rfc_del_emisor
receiptitem=Item+1|1|10.00
receiptitem-1=Item+2|2|3.00
receiptitem-2
receiptitem-3
receiptitem-4
receiptitem-5
receiptitem-6
```

BTW: Is verification of multiline fields tested?
