### ISSUE TITLE
As a moderator I want to define and verify multiline entries

### ISSUE THREAD

**Issue by KrzysztofMadejski** [the-engine-room/replication-sprint-02#13]
Forgot to reference: https://github.com/the-engine-room/replication-sprint-02/commit/0855a03fc3844bb58e0220e1d4456e2af95f0f23

**Comment by pisipite** [comment]
from the moderatior point of view the best would be to see all entered data by slugs next to each and have the possibility to choose between them at the same place. also to allow the modification of the data here. autofill & geolocation integration would help a lot to avoid minor differences!
