### ISSUE TITLE
translations english --> hungarian

### ISSUE THREAD

**Issue by lederberger** [the-engine-room/replication-sprint-02#16]
- [x] button - +1 ingatlan hozzáadása
- [x] Classic Vehicles - Gépjárművek
- [x] Gépjármű jellege list - a) személygépkocsi, b) tehergépjármű/autóbusz, c) motorkerékpár
- [x] year - év
- [x] +Add field - +1 gépjármű
- [x] list after Vízi vagy légi jármű jellege should be a single line text box
- [x] +Add field - +1 jármű
- [x] Artwork - Védett műalkotás, védett gyűjtemény és egyéb nagyobb értékű ingóságok
- [x] remove Védett műalkotás, védett gyűjtemén[ ]y és egyéb nagyobb értékű ingóság jellege (first option) from the list
- [x] +Add field - +1 műtárgy
- [ ] single line text after Értékpapír vagy egyéb befektetés - megnevezés
   *@krzysztofmadejski: There is singleline already. Can you recheck it? Should it be wider?*
   **_@lederberger_**: yes! there's need to be only one. i meant the inline text should be megnevezés instead of Értékpapír vagy egyéb befektetés.
- [x] HUF - HUF, EUR, CHF, GBP, USD, darab, egyéb
- [x] +Add field - +1 hozzáadása
- [ ] Takarék - Takarékbetétben elhelyezett megtakarítás
- [x] HUF - HUF, EUR, CHF, GBP, USD, darab, egyéb
- [x] +Add field - +1 hozzáadása
- [x] HUF - HUF, EUR, CHF, GBP, USD, darab, egyéb
- [x] +Add field - +1 hozzáadása
- [x] Obligations - Pénzintézeti számlakövetelés vagy más pénzkövetelés
- [x] options[típusa]: a) pénzintézeti számlakövetelés, b) más számlakövetelés
- [x] HUF - HUF, EUR, CHF, GBP, USD, darab, egyéb
- [x] Debts - Tartozások
- [x] tartozás típusa [list]: 1. köztartozás, 2. pénzintézeti, 3. magánszemélyi
- [x] HUF - HUF, EUR, CHF, GBP, USD, darab, egyéb
- [x] +Add entry - +1 tartozás
- [x] Comments - Egyéb közlendők
- [x] Szünetelteti - Szünetelteti?
- [x] HUF - HUF, EUR, CHF, GBP, USD, darab, egyéb
- [x] frequency - gyakoriság
- [x] +Add entry - +1 hozzáadása
- [ ] Formája [list] - Bt., erdőbirtoklási társulás, Kft., nonprofit Kft., Nyrt., szövetkezet, ügyvédi iroda, Zrt., egyéb
    *@krzysztofmadejski: if user chooses "egyéb" should he have input to fill as other, or is it literally "egyéb" in the form?
    *@lederberger: is it possible to have input to fill within the drop down? if yes, perfect! otherwise keep it like now.
- [x] move Érdekeltség formája keletkezéskor into "disabled option"
- [ ] Érdekeltség formája keletkezéskor [list] - alapító, beltag, kültag, részvényes, tulajdonos, egyéb
  *If someone chooses "egyéb" (other) should there be a textbox to fill the value? or does it literally means "egyeb"?*
    *@lederberger: is it possible to have input to fill within the drop down? if yes, perfect! otherwise keep it like now.
- [x] move Érdekeltség formája jelenleg into "disabled option"
- [x] Érdekeltség formája jelenleg [list] - alapító, beltag, kültag, részvényes, tulajdonos, egyéb
- [x] Érdekeltség keletkezéskori aránya - Érdekeltség aránya keletkezéskor
- [x] Érdekeltség keletkezéskori aránya jelenleg - Érdekeltség aránya jelenleg
- [ ] Tisztség [list] - beltag, elnök, igazgatóság elnöke, képviselő, kültag, szüneteltetve, tag, ügyvezető, egyéb
   *What about egyeb?*
    *@lederberger: is it possible to have input to fill within the drop down? if yes, perfect! otherwise keep it like now.
- [x] +add entry - +1 érdekeltség
- [x] Benefits - Juttatás
- [x] amount - értéke
- [x] [list] - HUF, törvényben alapján
- [x] +add entry - +1 juttatás
- [x] ajándék megnevezése should be single line text
- [x] HUF [list] - HUF, törvényben alapján
- [x] +add entry - +1 ajándék
- [x] Subsidies - Támogatások
- [x] pénznem [list] - HUF, EUR, CHF, GBP, USD, darab, egyéb
- [x] +add entry - +1 támogatás
- [x] Liberate - Felszabadítom!

**Comment by KrzysztofMadejski** [comment]
I've changed most of the texts from the list above. @lederberger please go and check boxes where it's ok. Where I had any doubts I've asked some questions. Please comment on them.

Also I'm missing:
- *if any* (next to Gépjárművek)
- missing values for  `<select name=artwork_acq[]" title="ownership">` in the *Védett műalkotás, védett gyűjtemény és egyéb nagyobb értékű ingóságok* section (first box in second line) 
  - need translation for *ownership*
- missing values for *Juttatás megnevezése* in *Juttatás* section (second box)

Regarding currency options: HUF - HUF, EUR, CHF, GBP, USD, darab, egyéb
- What does *darab* mean?
- If someone chooses "egyéb" (other) should there be a textbox to fill the value? or is it literaly written egyeb in the original form?

Also: which "Felszabadítom!" button of the two do you prefer?

**Comment by lederberger** [comment]
Thanks!
- we don't need if any. instead we need an opening question "Nyilatkozik-e..." (if there's any...)
"Nyilatkozott-e valamilyen nagy értékű ingóságról (járművek, műtárgyak)?"
- values for _Védett műalkotás, védett gyűjtemény és egyéb nagyobb értékű_ ingóságok: adás-vétel, ajándékozás, bérlés, lízing, öröklés, egyéb.
- egyéb: is it possible to have input to fill for "other" within the drop down? if yes, perfect! otherwise keep it like now.
- ownership --> Szerzés jogcíme
- if it's possible to have a drop down with an empty other field (like the question of egyéb) than include these: iPhone, irodahasználat, lakáshasználat, laptop, Lenovo laptop, mobiltelefon, Samsung mobiltelefon, személygépkocsi használat, telefonkártya, üzemanyagkártya. if that's not possible, than change it to a single line text field.

- darab means number of pieces.
- yes, have a textbox for egyéb in this case too, if possible.

I prefer the long button at the end.

Huge thanks!

**Comment by pisipite** [comment]
EN-->HUN

at _Védett műalkotás, védett gyűjtemény és egyéb nagyobb értékű ingóságok_
- [x] ownership - Szerzés jogcíme
- [x] list to contain same as above

and some more HUN-->HUN translation
- [x]  Jövedelemnyilatkozat - Nyilatkozik-e egyéb jövedelmeiről (Jövedelemnyilatkozat)?
- [x] Gazdasági érdekeltségi nyilatkozat - Nyilatkozik-e gazdasági érdekeltségekről?

**Comment by KrzysztofMadejski** [comment]
@IronRunes would you have time to work on that?

**Comment by IronRunes** [comment]
@KrzysztofMadejski  i believe most of it is done. I'm looking into fixing another small issue, will look into more tweaking tonight.

**Comment by KrzysztofMadejski** [comment]
It has worked so for the sake of keeping Github clean I will close it.
