### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by lederberger** [the-engine-room/replication-sprint-02#17]
- [x] - add a if there's any... question before vehicles
"Nyilatkozott-e valamilyen nagy értékű ingóságról (járművek, műtárgyak)?
- [x] - delete if any (at vehicles)
- [x] - list after Vízi vagy légi jármű jellege should be a single line text box
- [x] - remove Védett műalkotás, védett gyűjtemény és egyéb nagyobb értékű ingóság jellege (first option) from the list
- [x] - make disabled options more visible
- [x] - move Érdekeltség formája keletkezéskor into "disabled option"
- [x] - move Érdekeltség formája jelenleg into "disabled option"
- [x] - "Benefits (juttatások) drop down list should be either single line text or autofill 
- [x] - ajándék megnevezése should be single line text

**Comment by pisipite** [comment]
**things to fix**

- [x] - can you change background colour on the landing page to #f39a00 (in line with cover picture).
- [x] - if i open and close properties section (Nyilatkozott-e valamilyen ingatlanról?) the plus1 property stays visible. same with company info section (Gazdasági érdekeltségi nyilatkozat).
- [x] - we need an opening question "Nyilatkozik-e..." (if there's any...) before vehicles like at other secions. "Nyilatkozott-e valamilyen nagy értékű ingóságról (járművek, műtárgyak)?"
- [x] - pdf on the left side goes up with scrolling down.

**bigger issues**
- will you have time for the help bubbles? we wrote the texts and locations for them into two .txt files which were on the server (k-monitor folder).
- how's the export? from the admin it's gonna be Export all answers to CSV, right? do you see possible the syncing with vagyonkereső json (https://theengineroom.slack.com/files/tin/F3SJF3TMJ/vagyonkereso-export.zip)?
- will google maps integration and autofill work?
- with newsletter (hírlevél) can we go back to only a check box that doesn't navigate from the page. that's much better even without mailchimp integration.
