### ISSUE TITLE
Provide baseline for statistics

### ISSUE THREAD

**Issue by KrzysztofMadejski** [the-engine-room/replication-sprint-02#18]
hardcoded statistics from previous years as baseline

also: hide stats that cannot be computed yet

**Comment by KrzysztofMadejski** [comment]
@tingeber and @lederberger :
> 124 volunteers
397 documents
99 hours
(yes we’re moving to hours, the calculation is 16 minutes per document)

**Comment by KrzysztofMadejski** [comment]
Progress bar is only measuring this year declarations. Should it be adjusted to incorporate this baseline as well?

**Comment by pisipite** [comment]
leave it where it is now. i like that's near to the CTA button.
