### ISSUE TITLE
What if all declarations has been verified?

### ISSUE THREAD

**Issue by KrzysztofMadejski** [the-engine-room/replication-sprint-02#19]
How should body copy change? @lederberger? Something like "Well done! We've liberated all declarations for 2016! Join us again on 2018.01.31 for a 4th Vagyonnysialala Hajnala."

Should buttons "Tegyél átláthatóbbá egy képviselőt!" and "Kezdj bele!" be removed? Or just change the text and remove the link so it becomes a message?

CC: @tingeber 
PS. Attilla, please do create your own github acount :)

**Comment by pisipite** [comment]
> Elértük a 100 százalékos feldolgozottságot a 2016-os nyilatkozatok tekintetében! Nagyszerűek vagytok!
> Csatlakozz hozzánk jövőre is! Az elkészült adatbázist letöltheted [innen](link to the final database), vagy hamarosan a [Vagyonkereső.hu](http://vagyonkereso.hu)-ról. 
> 
> Ha fontosnak tartod a munkánkat, [támogasd te is a K-Monitort!](http://k-monitor.hu/tamogatas)

yes, please remove buttons for this page.

will be the final database available as soon as all of the documents verified?

**Comment by KrzysztofMadejski** [comment]
Implemented here: https://github.com/the-engine-room/replication-sprint-02/commit/13cc10804b5712bafb162a5fcef2f1a049616049
