### ISSUE TITLE
Combine dates in single field

### ISSUE THREAD

**Issue by KrzysztofMadejski** [the-engine-room/replication-sprint-02#20]
@IronRunes there can be different widgets showing date so I think it's the best to handle it in JS. If you don't have time let me know where can I tap into form submit

**Comment by IronRunes** [comment]
@KrzysztofMadejski AFAIK the form submission isn't handled via JS at all (just standard POST to action attribute). We can implement a JS submit though.
I believe we need to combine the the dates for each widget into a single string? Note that we have multilined date widgets within multilined widgets (ie acquisition dates (can be multiple) within building ownership (can be multiple)).

**Comment by KrzysztofMadejski** [comment]
So maybe this should work even without JS.. Ok, let me handle it in the backend.
