### ISSUE TITLE
What types of documents are supported in viewer? 

### ISSUE THREAD

**Issue by KrzysztofMadejski** [the-engine-room/replication-sprint-02#3]
I couldn't find any list of supported formats.

I've tried png and it seems it doesn't work.

**Comment by georgeslabreche** [comment]
@KrzysztofMadejski as far as I know, Crowdata only supports PDF. Any other format will require support to be built-in. If you look at @the-engine-room/library entry on [Microtasking](https://library.theengineroom.org/microtasking/), there is a platform evaluation grid which indicates that the _"Allowed Data Formats"_  for Crowdata is only "Text."

**Comment by KrzysztofMadejski** [comment]
Ok!

How do you feel about removing `document_set.template_function` from the admin and embedding pdf viewer it in the code based on the document extension. I found it more intuitive than having jvascript code in the admin.

I'd rewrite this section: https://github.com/the-engine-room/replication-sprint-02/blob/master/crowdataapp/templates/transcription_new.html#L73-L76

**Comment by georgeslabreche** [comment]
@KrzysztofMadejski Sounds good!
