### ISSUE TITLE
Input for "other" if this option was chosen in select

### ISSUE THREAD

**Issue by KrzysztofMadejski** [the-engine-room/replication-sprint-02#30]
That relates to #16 and #17.

For example now, in Buildings section (Nyilatkozott-e valamilyen ingatlanról?) in first combo of "Szerzés jogcíme" there is "egyeb" (other) option. If clicked nothing happens whether I would expect for hidden `<input name="acquisition-other[0][]" id="select1-other" class="hidden form-control other-input" placeholder="Enter value for the selection here" type="text">` to be shown.

**Comment by IronRunes** [comment]
@KrzysztofMadejski this is because the value of the option was checked to append the extra input field. before it was "other", changing it to "egyeb". ;)

**Comment by KrzysztofMadejski** [comment]
Generalized here: https://github.com/themoonsheep/moonsheep/issues/117
